import { RoleName } from 'generated/prisma/enums';
import { PERMISSIONS } from './permission.constant';

export const ROLE_PERMISSIONS = {
  [RoleName.super_admin]: Object.values(PERMISSIONS),

  [RoleName.admin]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.INVESTMENT_VIEW,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.REPAYMENTSCHEDULE_CREATE,
    PERMISSIONS.PAYOUTSCHEDULE_CREATE,
  ],

  [RoleName.staff]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.INVESTMENT_VIEW,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.REPAYMENTSCHEDULE_CREATE,
    PERMISSIONS.PAYOUTSCHEDULE_CREATE,
  ],

  [RoleName.user]: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.INVESTMENT_VIEW,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYOUT_CREATE,
  ],
};
